# Generated by Django 5.0.6 on 2024-05-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='relative_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
