# Generated by Django 5.0.6 on 2024-05-23 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_link',
            field=models.URLField(default='https://www.bing.com/'),
            preserve_default=False,
        ),
    ]
