# Generated by Django 5.0.6 on 2024-05-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_job_relative_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='relative_time',
        ),
    ]
