# Generated by Django 5.0.6 on 2024-05-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_remove_job_relative_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_link',
            field=models.URLField(),
        ),
    ]
